language: python

python:
  - 3.8.2

install:
  - pip install -r requirements.txt

before_script:
  - py manage.py migrate
  - py manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test

after_script:
  - coveralls
